:development:
  :adapter: <%= ENV['DATABASE_ADAPTER'] %>
  :host: <%= ENV['DATABASE_HOST'] %>
  :database: <%= ENV['DATABASE_DB'] %>
  :user: <%= ENV['DATABASE_USER'] %>
  :password: <%= ENV['DATABASE_PASSWORD'] %>
:test:
  :adapter: <%= ENV['DATABASE_ADAPTER'] %>
  :host: <%= ENV['DATABASE_HOST'] %>
  :database: <%= ENV['DATABASE_DB'] %>
  :user: <%= ENV['DATABASE_USER'] %>
  :password: <%= ENV['DATABASE_PASSWORD'] %>
:production:
  :adapter: <%= ENV['DATABASE_ADAPTER'] %>
  :host: <%= ENV['DATABASE_HOST'] %>
  :database: <%= ENV['DATABASE_DB'] %>
  :user: <%= ENV['DATABASE_USER'] %>
  :password: <%= ENV['DATABASE_PASSWORD'] %>